---
# Deployment for deploying Swap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost
        env:
        - name: url
          value: https://localhost
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: "{{ mysql_host }}"
        - name: database__connection__user
          value: "{{ mysql_user }}"
        - name: database__connection__password
          value: "{{ mysql_password }}"
        - name: database__connection__database
          value: "{{ mysql_database }}"
        ports:
        - containerPort: 8000