---

# ansible-galaxy collection install kubernetes.core
# pip install kubernetes
- name: Deploy ghost
  kubernetes.core.k8s:
    state: absent
    src: "{{ghost_deploy_file}}"

- name: Deploy ghost Service
  kubernetes.core.k8s:
    state: present
    src: "{{ ghost_service_file }}"
  