---

# ansible-galaxy collection install kubernetes.core
# pip install kubernetes

- name: Search for all Pods labelled app=mysql
  kubernetes.core.k8s_info:
    namespace: default
    kind: Pod
    label_selectors:
      - app = mysql
  register: pod_list

- name: Search for all Nodes
  kubernetes.core.k8s_info:
    namespace: default
    kind: Node
  register: node_list

#- name: Pause for 20 sec to build mysql
#  ansible.builtin.pause:
#    seconds: 20

- name: Replace old hostname with new hostname
  ansible.builtin.replace:
    path: inventory/gcp.yml
    regexp: 'ghost_ip: (?:[0-9]{1,3}\.){3}[0-9]{1,3}'
    replace: 'ghost_ip: "{{ node_list.resources.0.status.addresses.1.address }}"'


- name: Wait for mysql pods become ready
  shell: "kubectl wait --namespace=default --for=condition=Ready pods --selector app=mysql --timeout=600s"

- name: Deploy ghost
  kubernetes.core.k8s:
    state: present
    template: "{{ghost_deploy_file}}"

- name: Deploy ghost Service
  kubernetes.core.k8s:
    state: present
    template: "{{ ghost_service_file }}"
  
- name: Wait for ghost pods become ready
  shell: "kubectl wait --namespace=default --for=condition=Ready pods --selector app=ghost --timeout=600s"

#- name: Pause for 20 sec to build ghst
#  ansible.builtin.pause:
#    seconds: 20

- name: Create Ghost admin
  kubernetes.core.k8s_exec:
    namespace: default
    pod: "{{ pod_list.resources.0.metadata.name }}"
    command: mysql -h "{{ mysql_host }}" "{{ mysql_database }}" -e "update users set name='"{{ admin_user_name }}"', password='"{{ admin_password }}"', email='"{{ admin_email }}"', status='active' where id=1"
