---
# Deployment for deploying Swap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost
        env:
        - name: url
          value: http://{{ node_list.resources.0.status.addresses.1.address }}:30007/
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: ghost
        - name: database__connection__password
          value: passwordSegura
        - name: database__connection__database
          value: ghost-db
        - name: mail__transport
          value: "SMTP"
        - name: mail__options__service
          value: "Mailgun"
        - name: mail__options__auth__user
          value: postmaster@sandboxb62ae82c262f477fb1ad1320e761a8ea.mailgun.org
        - name: mail__options__auth__pass
          value: 3d08ebd3b993e51da4a3d173429f6910-c2efc90c-a1931bed

        ports:
        - containerPort: 2368
      readinessProbe:
      exec:
        command:
        - ping http://{{ node_list.resources.0.status.addresses.1.address }}:30007/
      initialDelaySeconds: 5
