---
# Deployment for deploying Swap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: default
  labels:
    app: ghost
spec:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost
        env:
        - name: url
          value: http://{{ ghost_ip }}:{{ ghost_port }}/
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: ghost
        - name: database__connection__password
          value: passwordSegura
        - name: database__connection__database
          value: ghost-db
        - name: mail__transport
          value: "SMTP"
        - name: mail__options__service
          value: "Mailgun"
        - name: mail__options__auth__user
          value: "{{ mail_user }}"
        - name: mail__options__auth__pass
          value: "{{ mail_pass }}"

        ports:
        - containerPort: 2368
      readinessProbe:
      #exec:
        #command:
        #- ping http://{{ ghost_ip }}:30007/
      initialDelaySeconds: 5
