---
# Deployment for MySQL
apiVersion: apps/v1

kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env: # The variables below could be set on a ConfigMap object
        - name: MYSQL_DATABASE
          value: ghost-db
        - name: MYSQL_USER
          value: "ghost"
        - name: MYSQL_PASSWORD
          value: "passwordSegura" # Use Secret object in real usage
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true" 
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      readinessProbe:
      exec:
        command:
        - mysqladmin ping --silent
      initialDelaySeconds: 5
